site:
  title: Antora Docs
  start_page: component-b::index.adoc
content:
  sources:
  - url: https://github.com/mustafaokyay/antora_testumgebung.git
    branches: HEAD
  - url: https://github.com/mustafaokyay/antora_testumgebung.git
    branches: [master]
    start_path: documentation
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true